spring:
  application:
    name: apigw-order
  config:
    import: configserver:http://127.0.0.1:8888
  cloud:
    gateway:
      mvc:
        routes:
          - id: my-order-root1
            uri: lb://ORDER
            predicates:
              - Path=api/v1/order/**
server:
  port: ${MYPORT:9090}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-components: always
      show-details: always